name: Backup to Cloudflare
on:
  schedule:
    - cron: "30 20 * * *"
  workflow_dispatch:

jobs:
  backup-db:
    name: Backup DB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
          curl -L https://fly.io/install.sh | sh
          pip install -r requirements.txt
      - name: Backup
        run: |
          python backup.py
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_ID: ${{ secrets.R2_ACCESS_ID }}
          R2_ACCESS_SECRET: ${{ secrets.R2_ACCESS_SECRET }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          UPTIME_HEARTBEAT: ${{ secrets.UPTIME_HEARTBEAT }}
          APP_NAME: ${{ secrets.APP_NAME}}
      - name: Print Secrets
        run: |
          echo "FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}"
          echo "PGPASSWORD: ${{ secrets.PGPASSWORD }}"
          echo "R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}"
          echo "R2_ACCESS_ID: ${{ secrets.R2_ACCESS_ID }}"
          echo "R2_ACCESS_SECRET: ${{ secrets.R2_ACCESS_SECRET }}"
          echo "R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}"
          echo "UPTIME_HEARTBEAT: ${{ secrets.UPTIME_HEARTBEAT }}"
          echo "APP_NAME: ${{ secrets.APP_NAME}}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_ID: ${{ secrets.R2_ACCESS_ID }}
          R2_ACCESS_SECRET: ${{ secrets.R2_ACCESS_SECRET }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          UPTIME_HEARTBEAT: ${{ secrets.UPTIME_HEARTBEAT }}
          APP_NAME: ${{ secrets.APP_NAME}}
